name: VS Code Marketplace Release

on:
    release:
        types: [published]

jobs:
    publish-release:
        if: '!github.event.release.prerelease'
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Create env.ts file
              run: echo "export const TELEMETRY_KEY = '${{ secrets.TELEMETRY_KEY }}'" > src/env.ts
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: Install dependencies
              run: npm run clean-install
            - name: Build project
              run: npm run build
            - name: Install vsce
              run: npm install -g @vscode/vsce
            - name: Publish to VS Code Marketplace
              run: vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }}

    publish-prerelease:
        if: 'github.event.release.prerelease'
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Create env.ts file
              run: echo "export const TELEMETRY_KEY = '${{ secrets.TELEMETRY_KEY }}'" > src/env.ts
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: Install dependencies
              run: npm run clean-install
            - name: Build project
              run: npm run build
            - name: Install vsce
              run: npm install -g @vscode/vsce
            - name: Publish pre-release to VS Code Marketplace
              run: vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }} --pre-release

    publish-openvsx:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Create env.ts file
              run: echo "export const TELEMETRY_KEY = '${{ secrets.TELEMETRY_KEY }}'" > src/env.ts
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: Install dependencies
              run: npm run clean-install
            - name: Build project
              run: npm run build
            - name: Install ovsx
              run: npm install -g ovsx
            - name: Update publisher in package.json
              run: |
                  @echo off
                  findstr /v "\"publisher\": \"ackeeblockchain\"" package.json > temp.json
                  echo     "publisher": "AckeeBlockchainSecurity", >> temp.json
                  findstr /v "}" temp.json > package.json
                  echo } >> package.json
                  del temp.json
            - name: Publish to Open VSX Registry
              run: npx ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}
